language: ruby
script: bundle exec rspec spec

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode

  gemfile:
  - spec/gemfiles/Gemfile.rails-4.2.x
  - spec/gemfiles/Gemfile.rails-5.0.x
  - spec/gemfiles/Gemfile.rails-6.0.x

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-4.2.x.gemfile
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-5.0.x.gemfile
    - rvm: 1.9.3
      gemfile: spec/gemfiles/rails-6.0.x.gemfile
  fast_finish: true
